TramiteDigitalWeb/Controllers/AdministracionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TramiteDigitalWeb.Models;
using TramiteDigitalWeb.Models.classes;
using TramiteDigitalWeb.data_members;

namespace TramiteDigitalWeb.Controllers
{
    public class AdministracionController : Controller
    {
        private Boolean ValidaAcceso() {
            if (!string.IsNullOrEmpty(User.Identity.Name))
            {
                string[] response = Acceso.Valida(User.Identity.Name);
                if (Boolean.Parse(response[0]) == false)
                {
                    TempData["NoAdminPermissions"] = response[1];
                    return false;
                }
                return true;
            }
            return false;
        }

        private void InicializaVars(string returnUrl = null){
            ViewBag.ReturnUrl = returnUrl;
        }

#region Usuarios

        [Authorize]
        [HttpGet]
        public ActionResult Usuarios()
        {
            if (!ValidaAcceso()) return RedirectToAction("KillSession", "Account");

            InicializaVars();
            return View(AdministracionModel.ListadeUsuarios());
        }

        [Authorize]
        [HttpGet]
        public ActionResult Crear_Usuario()
        {
            if (!ValidaAcceso()) return RedirectToAction("KillSession", "Account"); 

            InicializaVars();
            return View(new ca_usuarios() { activo = true });
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear_Usuario(ca_usuarios Form)
        {
            if (!ValidaAcceso()) return RedirectToAction("KillSession", "Account"); 

            InicializaVars();
            if (ModelState.IsValid)
            {
                Boolean? response = AdministracionModel.CrearUsuario(Form);
                if (response != null) {
                    if (response == true) {
                        return RedirectToAction("Usuarios");
                    } else {
                        ModelState.AddModelError("", "El usuario ya se encuentra registrado, favor de revisar");
                    }
                }
                else
                    ModelState.AddModelError("", "Ocurrió un error al intentar agregar el usuario, favor de intentarlo de nuevo");
            }
            
            return View(Form);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Detalle_Usuario(int id_usuario)
        {
            if (!ValidaAcceso()) return RedirectToAction("KillSession", "Account"); 

            InicializaVars();

            ca_usuarios usuario = AdministracionModel.Get_Usuario(id_usuario);
            ViewBag.nodos_usuario = AdministracionModel.Get_NodosUsuario(id_usuario);
            return View(usuario);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Edita_Usuario(int id_usuario, string returnUrl)
        {
            if (!ValidaAcceso()) return RedirectToAction("KillSession", "Account");

            InicializaVars(returnUrl);

            ca_usuarios usuario = AdministracionModel.Get_Usuario(id_usuario);
            usuario.repetircontrasenia = usuario.contrasenia;
            return View(usuario);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edita_Usuario(ca_usuarios Form, string returnUrl)
        {
            if (!ValidaAcceso()) return RedirectToAction("KillSession", "Account"); 

            InicializaVars();
            if (ModelState.IsValid)
            {
                if (AdministracionModel.Edita_Usuario(Form))
                {
                    if (returnUrl != null)
                    {
                        return RedirectToLocal(returnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Usuarios");
                    }                    
                }
                else
                    ModelState.AddModelError("", "Ocurrió un error al intentar editar el usuario, favor de intentarlo de nuevo");
            }
            return View(Form);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Cambia_Contrasenia_Usuario(int id_usuario, string returnUrl)
        {
            if (!ValidaAcceso()) return RedirectToAction("KillSession", "Account");

            InicializaVars(returnUrl);

            ca_usuarios usuario = AdministracionModel.Get_Usuario(id_usuario);
            usuario.contrasenia = null;
            usuario.repetircontrasenia = null;
            return View(usuario);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cambia_Contrasenia_Usuario(ca_usuarios Form, string returnUrl)
        {
            if (!ValidaAcceso()) return RedirectToAction("KillSession", "Account"); 

            InicializaVars();
            if (ModelState.IsValid)
            {
                if (AdministracionModel.Cambia_Contrasenia(Form))
                {
                    if (returnUrl != null)
                    {
                        return RedirectToLocal(returnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Usuarios");
                    }
                }
                else
                    ModelState.AddModelError("", "Ocurrió un error al intentar cambiar contraseña del usuario, favor de intentarlo de nuevo");
            }
            return View(Form);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Eliminar_usuario(int id_usuario)
        {
            if (!ValidaAcceso()) return RedirectToAction("KillSession", "Account"); 

            InicializaVars();

            if (AdministracionModel.Elimina_Usuario(id_usuario))
            {
                ViewBag.Response = "Usuario eliminado con éxito";
                if (!ValidaAcceso()) return RedirectToAction("KillSession", "Account"); 
            }
            else
                ViewBag.Response = "Ocurrió un error al intentar eliminar el usuario, favor de intentarlo de nuevo";

            return RedirectToAction("Usuarios");
        }

#endregion Usuarios

#region Nodos
        [Authorize]
        [HttpGet]
        public ActionResult Nodos()
        {
            if (!ValidaAcceso()) return RedirectToAction("KillSession", "Account"); 

            InicializaVars();
            return View(AdministracionModel.ListadeNodos());
        }

        [Authorize]
        [HttpGet]
        public ActionResult Crear_Nodo()
        {
            if (!ValidaAcceso()) return RedirectToAction("KillSession", "Account"); 

            InicializaVars();
            return View(new ca_nodos() { activo = true });
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear_Nodo(ca_nodos Form)
        {
            if (!ValidaAcceso()) return RedirectToAction("KillSession", "Account"); 

            InicializaVars();
            if (ModelState.IsValid)
            {
                Boolean? response = AdministracionModel.CrearNodo(Form);
                if (response != null)
                {
                    if (response == true)
                    {
                        return RedirectToAction("Nodos");
                    }
                    else
                    {
                        ModelState.AddModelError("", "El nodo ya se encuentra registrado, favor de revisar");
                    }
                }
                else
                    ModelState.AddModelError("", "Ocurrió un error al intentar agregar el nodo, favor de intentarlo de nuevo");
            }

            return View(Form);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Detalle_Nodo(int id_nodo, Boolean partial = false)
        {
            if (!ValidaAcceso()) return RedirectToAction("KillSession", "Account"); 

            InicializaVars();

            if (!partial) 
                return View(AdministracionModel.Get_Nodo(id_nodo));
            else
                return View("Detalle_Nodo_Partial",AdministracionModel.Get_Nodo(id_nodo));
        }

        [Authorize]
        [HttpGet]
        public ActionResult Edita_Nodo(int id_nodo, string returnUrl)
        {
            if (!ValidaAcceso()) return RedirectToAction("KillSession", "Account");

            InicializaVars(returnUrl);
            return View(AdministracionModel.Get_Nodo(id_nodo));
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edita_Nodo(ca_nodos Form, string returnUrl)
        {
            if (!ValidaAcceso()) return RedirectToAction("KillSession", "Account"); 

            InicializaVars();
            if (ModelState.IsValid)
            {
                if (AdministracionModel.Edita_Nodo(Form))
                {
                    if (returnUrl != null)
                    {
                        return RedirectToLocal(returnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Nodos");
                    }                    
                }                    
                else
                    ModelState.AddModelError("", "Ocurrió un error al intentar editar el nodo, favor de intentarlo de nuevo");
            }
            return View(Form);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Eliminar_nodo(int id_nodo)
        {
            if (!ValidaAcceso()) return RedirectToAction("KillSession", "Account"); 

            InicializaVars();

            if (AdministracionModel.Elimina_Nodo(id_nodo))
            {
                ViewBag.Response = "Nodo eliminado con éxito";
            }
            else

TramiteDigitalWeb/Views/Administracion/Cambia_Contrasenia_Usuario.cshtml
<link href="@Url.Content("~/Content/Create_User.css")" rel="stylesheet" type="text/css" />

@model TramiteDigitalWeb.data_members.ca_usuarios

@{
    ViewBag.Title = "Cambiar contraseña";
}

<h2>@ViewBag.Title</h2>
<hr style="width: 70%;float: left;display: block;"/>

@using (Html.BeginForm("Cambia_Contrasenia_Usuario", "Administracion", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { style = "clear: both;" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Usuario</legend>

        @Html.HiddenFor(model => model.id)
        @Html.HiddenFor(model => model.usuario)
        @Html.HiddenFor(model => model.curp)
        @Html.HiddenFor(model => model.nombres)
        @Html.HiddenFor(model => model.apellido1)
        @Html.HiddenFor(model => model.apellido2)
        @Html.HiddenFor(model => model.telefono)
        @Html.HiddenFor(model => model.cargo)
        @Html.HiddenFor(model => model.activo)
        @Html.HiddenFor(model => model.es_administrador)

        <div class="editor-label">
            @Html.LabelFor(model => model.contrasenia)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.contrasenia)
            @Html.ValidationMessageFor(model => model.contrasenia)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.repetircontrasenia)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.repetircontrasenia)
            @Html.ValidationMessageFor(model => model.repetircontrasenia)
        </div>

        <p>
            <input type="submit" value="Guardar nueva contraseña" style="float:left;"  />
            @if (ViewBag.ReturnUrl == null)
            {
                @Html.ActionLink("Cancelar", "Usuarios", null, new { style = "float:left;text-decoration: none;margin-top:5px;background-color: lightcoral;border: 1px solid #787878;cursor: pointer;font-size: 1.2em;font-weight: 600;padding: 6px;margin-right: 8px;width: auto;" });
            } else {
                <a href="@ViewBag.ReturnUrl" style="float:left;text-decoration: none;margin-top:5px;background-color: lightcoral;border: 1px solid #787878;cursor: pointer;font-size: 1.2em;font-weight: 600;padding: 6px;margin-right: 8px;width: auto;">Cancelar</a>
            }
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TramiteDigitalWeb/Views/Administracion/Crear_Nodo.cshtml
<link href="@Url.Content("~/Content/Create_User.css")" rel="stylesheet" type="text/css" />

@model TramiteDigitalWeb.data_members.ca_nodos

@{
    ViewBag.Title = "Nuevo Nodo";
}

<h2>@ViewBag.Title</h2>
<hr style="width: 70%;float: left;display: block;"/>

@using (Html.BeginForm("Crear_Nodo", "Administracion", FormMethod.Post, new { style = "clear: both;" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Nodo</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.nodo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.nodo)
            @Html.ValidationMessageFor(model => model.nodo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.url_servicio_rest)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.url_servicio_rest)
            @Html.ValidationMessageFor(model => model.url_servicio_rest)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.usuario)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.usuario)
            @Html.ValidationMessageFor(model => model.usuario)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.contrasenia)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.contrasenia)
            @Html.ValidationMessageFor(model => model.contrasenia)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.activo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.activo)
            @Html.ValidationMessageFor(model => model.activo)
        </div>

        <p>            
            <input type="submit" value="Agregar nodo" style="float:left;" />
            @Html.ActionLink("Cancelar", "Nodos", null, new { style = "float:left;text-decoration: none;margin-top:5px;background-color: lightcoral;border: 1px solid #787878;cursor: pointer;font-size: 1.2em;font-weight: 600;padding: 6px;margin-right: 8px;width: auto;" })
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TramiteDigitalWeb/Views/Administracion/Crear_Usuario.cshtml
<link href="@Url.Content("~/Content/Create_User.css")" rel="stylesheet" type="text/css" />

@model TramiteDigitalWeb.data_members.ca_usuarios

@{
    ViewBag.Title = "Nuevo usuario";
}

<h2>@ViewBag.Title</h2>
<hr style="width: 70%;float: left;display: block;"/>

@using (Html.BeginForm("Crear_Usuario", "Administracion", FormMethod.Post, new { style = "clear: both;" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Usuario</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.usuario)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.usuario)
            @Html.ValidationMessageFor(model => model.usuario)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.contrasenia)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.contrasenia)
            @Html.ValidationMessageFor(model => model.contrasenia)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.repetircontrasenia)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.repetircontrasenia)
            @Html.ValidationMessageFor(model => model.repetircontrasenia)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.curp)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.curp)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.nombres)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.nombres)
            @Html.ValidationMessageFor(model => model.nombres)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.apellido1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.apellido1)
            @Html.ValidationMessageFor(model => model.apellido1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.apellido2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.apellido2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.telefono)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.telefono)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.cargo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.cargo)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.activo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.activo)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.es_administrador)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.es_administrador)
        </div>
        <p>            
            <input type="submit" value="Agregar usuario" style="float:left;" />
            @Html.ActionLink("Cancelar", "Usuarios", null, new { style = "float:left;text-decoration: none;margin-top:5px;background-color: lightcoral;border: 1px solid #787878;cursor: pointer;font-size: 1.2em;font-weight: 600;padding: 6px;margin-right: 8px;width: auto;" })
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TramiteDigitalWeb/Views/Administracion/Create.cshtml
<link href="@Url.Content("~/Content/Create_User.css")" rel="stylesheet" type="text/css" />

@model TramiteDigitalWeb.data_members.ca_usuarios

@{
    ViewBag.Title = "Nuevo usuario";
}

<h2>@ViewBag.Title</h2>
<hr style="width: 70%;float: left;display: block;"/>

@using (Html.BeginForm("Create", "Administracion", FormMethod.Post, new { style="clear: both;" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Usuario</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.usuario)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.usuario)
            @Html.ValidationMessageFor(model => model.usuario)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.contrasenia)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.contrasenia)
            @Html.ValidationMessageFor(model => model.contrasenia)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.repetircontrasenia)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.repetircontrasenia)
            @Html.ValidationMessageFor(model => model.repetircontrasenia)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.curp)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.curp)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.nombres)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.nombres)
            @Html.ValidationMessageFor(model => model.nombres)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.apellido1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.apellido1)
            @Html.ValidationMessageFor(model => model.apellido1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.apellido2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.apellido2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.telefono)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.telefono)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.cargo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.cargo)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.activo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.activo)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.es_administrador)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.es_administrador)
        </div>
        <p>            
            <input type="submit" value="Agregar usuario" style="float:left;" />
            @Html.ActionLink("Cancelar", "Usuarios", null, new { style = "float:left;text-decoration: none;margin-top:5px;background-color: lightcoral;border: 1px solid #787878;cursor: pointer;font-size: 1.2em;font-weight: 600;padding: 6px;margin-right: 8px;width: auto;" })
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TramiteDigitalWeb/Views/Administracion/Edita_Nodo.cshtml
<link href="@Url.Content("~/Content/Create_User.css")" rel="stylesheet" type="text/css" />

@model TramiteDigitalWeb.data_members.ca_nodos

@{
    ViewBag.Title = "Edita nodo";
}

<h2>@ViewBag.Title</h2>
<hr style="width: 70%;float: left;display: block;"/>

@using (Html.BeginForm("Edita_Nodo", "Administracion", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { style = "clear: both;" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Nodo</legend>

        @Html.HiddenFor(model => model.id)
        @Html.HiddenFor(model => model.nodo)

        <div class="editor-label">
            @Html.LabelFor(model => model.url_servicio_rest)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.url_servicio_rest)
            @Html.ValidationMessageFor(model => model.url_servicio_rest)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.usuario)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.usuario)
            @Html.ValidationMessageFor(model => model.usuario)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.contrasenia)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.contrasenia)
            @Html.ValidationMessageFor(model => model.contrasenia)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.activo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.activo)
            @Html.ValidationMessageFor(model => model.activo)
        </div>

        <p>
            

            <input type="submit" value="Guardar cambios" style="float:left;"  />
            
            @if (ViewBag.ReturnUrl != null)
            {
                <a href="@ViewBag.ReturnUrl" style="float:left;text-decoration: none;margin-top:5px;background-color: lightcoral;border: 1px solid #787878;cursor: pointer;font-size: 1.2em;font-weight: 600;padding: 6px;margin-right: 8px;width: auto;">Cancelar</a>
            }
            else
            {
                @Html.ActionLink("Cancelar", "Nodos", null, new { style = "float:left;text-decoration: none;margin-top:5px;background-color: lightcoral;border: 1px solid #787878;cursor: pointer;font-size: 1.2em;font-weight: 600;padding: 6px;margin-right: 8px;width: auto;" })            
            }
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TramiteDigitalWeb/Views/Administracion/Edita_Usuario.cshtml
<link href="@Url.Content("~/Content/Create_User.css")" rel="stylesheet" type="text/css" />

@model TramiteDigitalWeb.data_members.ca_usuarios

@{
    ViewBag.Title = "Editar usuario";
}

<h2>@ViewBag.Title</h2>
<hr style="width: 70%;float: left;display: block;"/>

@using (
    Html.BeginForm("Edita_Usuario", "Administracion", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { style = "clear: both;" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Usuario</legend>

        @Html.HiddenFor(model => model.id)
        @Html.HiddenFor(model => model.contrasenia)
        @Html.HiddenFor(model => model.repetircontrasenia)
        @Html.HiddenFor(model => model.usuario)

        <div class="editor-label">
            @Html.LabelFor(model => model.curp)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.curp)
            @Html.ValidationMessageFor(model => model.curp)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.nombres)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.nombres)
            @Html.ValidationMessageFor(model => model.nombres)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.apellido1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.apellido1)
            @Html.ValidationMessageFor(model => model.apellido1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.apellido2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.apellido2)
            @Html.ValidationMessageFor(model => model.apellido2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.telefono)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.telefono)
            @Html.ValidationMessageFor(model => model.telefono)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.cargo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.cargo)
            @Html.ValidationMessageFor(model => model.cargo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.activo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.activo)
            @Html.ValidationMessageFor(model => model.activo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.es_administrador)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.es_administrador)
            @Html.ValidationMessageFor(model => model.es_administrador)
        </div>

        <p>
            <input type="submit" value="Guardar cambios" style="float:left;"  />
            
            @if (ViewBag.ReturnUrl != null)
            {
                <a href="@ViewBag.ReturnUrl" style="float:left;text-decoration: none;margin-top:5px;background-color: lightcoral;border: 1px solid #787878;cursor: pointer;font-size: 1.2em;font-weight: 600;padding: 6px;margin-right: 8px;width: auto;">Cancelar</a>
            }
            else {             
                @Html.ActionLink("Cancelar", "Usuarios", null, new { style = "float:left;text-decoration: none;margin-top:5px;background-color: lightcoral;border: 1px solid #787878;cursor: pointer;font-size: 1.2em;font-weight: 600;padding: 6px;margin-right: 8px;width: auto;" })            
            }
            
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}